name = "paint"
version = "0.3.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Make drawings, animations, and games (HTML Canvas)"
licences = ["MIT"]
repository = { type = "github", user = "adelhult", repo = "paint" }
links = [
    { title = "Visual examples", href = "https://adelhult.github.io/paint/" },
]
dev-dependencies = { gleeunit = ">= 1.6.1 and < 2.0.0" }
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.


[dependencies]
gleam_stdlib = ">= 0.58.0 and < 2.0.0"
gleam_community_colour = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
