name = "demo"
version = "0.1.0"
target = "javascript"

[dependencies]
paint = { path = "./../" }
gleam_community_colour = ">= 2.0.0 and < 3.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"
reference_this = ">= 0.1.0 and < 1.0.0"


[tools.lustre.html]
title = "Paint"
stylesheets = [
  { href = "/style.css" }
]
scripts = [
    { src = "./highlight.mjs", type = "module" }
]
meta = [
    { name="theme-color", content="#ABDAFC" }
]
links = [
    { rel = "preconnect", href = "https://fonts.googleapis.com" },
    { rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = "anonymous" },
    { rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Lexend:wght@100..900&display=swap" },
]
