name: Build examples

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.6.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Build website
        run: |
          cd website
          gleam deps download
          gleam run -m reference_this -- --allow-all-ext src/examples src/examples_code.gleam
          gleam run -m lustre/dev build app --minify
          mkdir -p dist
          cp index.html dist/index.html
          cp -r priv dist/priv
          sed -i 's|priv/static/demo.mjs|paint/priv/static/demo.min.mjs|' dist/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website/dist"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
