name: Build examples

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.3.2"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Build examples
        run: |
          cd examples
          gleam deps download
          gleam build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # TODO: A bit wasteful to grab all the build artifacts...
          path: "./examples/"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
